# .github/workflows/build-android.yml

name: Build Android Example APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # --- THE ONLY CHANGE THAT MATTERS ---
      # We are upgrading the engine to match the tools' requirements.
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Back to the simple version, as it will now work with Java 17.
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install dependencies
        run: npm install
        working-directory: ./example

      - name: Make gradlew executable
        run: chmod +x ./gradlew
        working-directory: ./example/android

      - name: Build debug APK
        run: ./gradlew assembleDebug
        working-directory: ./example/android

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: skyth-example-apk
          path: example/android/app/build/outputs/apk/debug/app-debug.apk