# .github/workflows/build-android.yml

name: Build Android Example APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      # --- THE FIX IS HERE ---
      # We are now commanding it to use specific, older tools compatible with Java 11.
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3 # v3 of the action is still fine
        with:
          api-level: 33 # Target a specific, stable API level
          build-tools: 33.0.0 # Use a specific version of the build tools
          ndk: 23.1.7779620 # Pin the NDK version for consistency

      - name: Install dependencies
        run: npm install
        working-directory: ./example

      - name: Make gradlew executable
        run: chmod +x ./gradlew
        working-directory: ./example/android

      - name: Build debug APK
        run: ./gradlew assembleDebug
        working-directory: ./example/android

      # --- UPDATED ARTIFACT UPLOAD ---
      - name: Upload APK
        uses: actions/upload-artifact@v4 # Use the latest version as you suggested
        with:
          name: skyth-example-apk
          path: example/android/app/build/outputs/apk/debug/app-debug.apk