name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  release:
    if: github.event.head_commit.author.email != 'VladlenskiyReleaseBot@users.noreply.github.com'
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App token
        id: generate_token
        uses: peter-murray/workflow-application-token-action@v2
        with:
          application_id: ${{ secrets.APP_ID }}
          application_private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: actions/checkout@v3
        with:
          token: ${{ steps.generate_token.outputs.token }}

      - uses: actions/setup-node@v3
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'

      - name: Set git user
        run: |
          git config --global user.name "Vladlenskiy Release Bot"
          git config --global user.email "VladlenskiyReleaseBot@users.noreply.github.com"

      - run: yarn install --frozen-lockfile
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Release
        run: yarn release --ci
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Push changes with App token
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/vladlenskiy/react-native-tdlib.git HEAD:master --follow-tags